project:
  type: book
  output-dir: _book
  resources:
    - workshop3/dashboardA.qmd  # Keep it listed so it gets rendered

book:
  title: "BM424 Clinical Microbiology Pandemic Preparedness Workshops"
  cover-image: sipbs_compbio_800.png
  favicon: icon_32.png
  page-navigation: false
    
  # Sets the page footer text/images
  page-footer:
    center: |
      BM424 Workshops · 2024-25 · Dr Morgan Feeney
  author: "Dr Morgan Feeney"
  date: "28/02/2025"

  # Define chapters and contents here
  chapters:
    - index.qmd
    #display these files for workshop 4
    #- workshop4.qmd
    #- part: "Workshop 4, Group Information"
      #chapters:
        #- workshop4/4A.qmd
        #- workshop4/4B.qmd
        #- workshop4/4C.qmd
        #- workshop4/4D.qmd
        #- workshop4/4E.qmd
        #- workshop4/4F.qmd
        #- workshop4/4G.qmd
        #- workshop4/4H.qmd
        #- workshop4/4I1.qmd
        #- workshop4/4I2.qmd
        
    - workshop3.qmd
    - part: "Workshop 3, Group Information"
      chapters:
        - workshop3/3A.qmd
        - workshop3/dashboardA.qmd
        - workshop3/3B.qmd
        - workshop3/dashboardB.qmd
        - workshop3/3C.qmd
        - workshop3/dashboardC.qmd
        - workshop3/3D.qmd
        - workshop3/dashboardD.qmd
        - workshop3/3E.qmd
        - workshop3/dashboardE.qmd
        - workshop3/3F.qmd
        - workshop3/dashboardF.qmd
        - workshop3/3G.qmd
        - workshop3/dashboardG.qmd
        - workshop3/3H.qmd
        - workshop3/dashboardH.qmd
        - workshop3/3I.qmd
        - workshop3/dashboardI.qmd

# Formatting and theme; may not need to be changed
format:
  html:
    theme: cosmo
    code-link: true
    fig-cap: true
    author-meta: "Leighton Pritchard"
    sidebar:
      style: "always"

# Freeze output before pushing modifications to the repository when publishing
# Should not need changing
execute:
  freeze: auto
